name: Criar API HML

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Conferir estrutura do projeto
        run: |
          echo "Diretório atual:"
          pwd
          echo "Arquivos:"
          ls -la
          echo "Estrutura:"
          find . -maxdepth 3 -type f | sort

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir e publicar API HML
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ghcr.io/madsonpersonal-max/cabana-gestao-api:hml
